modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="apes_strong_together"
version="1.0.0"
displayName="apes strong together"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/apes-strong-together"
authors="Daniel Rosenberg, MCreator"

[[dependencies.apes_strong_together]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




